head	1.1;
access;
symbols;
locks;
comment	@# @;


1.1
date	2006.10.03.13.35.23;	author Average;	state Exp;
branches;
next	;


desc
@@


1.1
log
@Initial revision
@
text
@(*
** Module   :MULTIBAR.H
** Abstract :Constants for MULTIBAR.C
**
** Copyright (C) Sergey I. Yevtushenko
** Log: Sun  08/02/98   Refined
*)

const
  MAIN_FRAME    =255;
  ID_FILEMENU   =256;
  ID_EDITMENU   =258;

  ID_TOOLBAR    =1045;
  ID_LPANE      =1046;
  ID_RPANE      =1047;
  ID_NOTEBOOK   =1045;
  ID_STATUS     =1050;
  ID_LIST       =1051;
  ID_MLE        =1052;
  ID_TOP        =1053;

  IDB_FILENEW   =301;
  IDB_FILEOPEN  =302;
  IDB_FILESAVE  =303;
  IDB_FILSAVAS  =304;
  IDB_EXIT      =305;
  IDB_EDITCOPY  =306;
  IDB_EDITCUT   =307;
  IDB_EDITFIND  =308;
  IDB_EDITFNNX  =309;
  IDB_EDITPAST  =310;
  IDB_EDITREPL  =311;
  IDB_EDITUNDO  =312;
  IDB_HELP      =313;
  IDB_ABOUT     =314;

  IDB_HILIGHT   =400;@
